embeddings:
  model_name:  "BAAI/bge-small-en-v1.5" #'BAAI/bge-m3'
  device: cuda

llm:
  model_name: "qwen/qwen3-30b-a3b:free"
  temperature: 0.6
  top_k: 20
  top_p: 0.95
  repeat_penalty: 1.0
  
rag:
  k_text: 2
  k_equation: 3
  k_table: 1
  debug: True