embeddings:
  model_name:  "bge-m3"

llm:
  model_name: "qwen/qwen3-30b-a3b:free"
  local: False
  temperature: 0.6
  top_k: 20
  top_p: 0.95
  repeat_penalty: 1.0
  
rag:
  k_text: 2
  k_equation: 3
  k_table: 1
  debug: True